# Generated by Django 5.0.4 on 2024-04-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('abbreviated_name', models.CharField(max_length=255)),
                ('licence_number', models.CharField(max_length=16)),
                ('inn', models.IntegerField()),
                ('date_of_registration', models.DateField()),
                ('address', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(max_length=32)),
                ('termination_date', models.DateField()),
            ],
        ),
    ]
