# Generated by Django 5.0.4 on 2024-04-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='abbreviated_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
