# Generated by Django 5.0.4 on 2024-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0003_alter_table_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
