# Generated by Django 5.0.4 on 2024-04-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0004_alter_table_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='inn',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
