# Generated by Django 5.0.4 on 2024-04-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_table', '0005_alter_table_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='licence_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
